# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classipy2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1043, 799)
        MainWindow.setMaximumSize(QtCore.QSize(1043, 799))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/classipy2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(790, 50, 241, 681))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.gridLayout = QtGui.QGridLayout(self.verticalLayoutWidget_3)
        self.gridLayout.setContentsMargins(-1, -1, 3, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolBox = QtGui.QToolBox(self.verticalLayoutWidget_3)
        self.toolBox.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.toolBox.setPalette(palette)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 237, 571))
        self.page.setObjectName(_fromUtf8("page"))
        self.formLayoutWidget = QtGui.QWidget(self.page)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 211, 111))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.dbHostEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.dbHostEdit.setObjectName(_fromUtf8("dbHostEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dbHostEdit)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.dbUserEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.dbUserEdit.setObjectName(_fromUtf8("dbUserEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dbUserEdit)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.dbPasswdEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.dbPasswdEdit.setInputMask(_fromUtf8(""))
        self.dbPasswdEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.dbPasswdEdit.setObjectName(_fromUtf8("dbPasswdEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dbPasswdEdit)
        self.actionConnectDb = QtGui.QPushButton(self.formLayoutWidget)
        self.actionConnectDb.setObjectName(_fromUtf8("actionConnectDb"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.actionConnectDb)
        self.formLayoutWidget_3 = QtGui.QWidget(self.page)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 140, 211, 111))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.comboDatabases = QtGui.QComboBox(self.formLayoutWidget_3)
        self.comboDatabases.setEnabled(False)
        self.comboDatabases.setObjectName(_fromUtf8("comboDatabases"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboDatabases)
        self.actionSetActiveDb = QtGui.QPushButton(self.formLayoutWidget_3)
        self.actionSetActiveDb.setEnabled(False)
        self.actionSetActiveDb.setObjectName(_fromUtf8("actionSetActiveDb"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.actionSetActiveDb)
        self.activeDb = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.activeDb.setEnabled(False)
        self.activeDb.setObjectName(_fromUtf8("activeDb"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.activeDb)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.actionCreateNewDb = QtGui.QPushButton(self.formLayoutWidget_3)
        self.actionCreateNewDb.setEnabled(False)
        self.actionCreateNewDb.setObjectName(_fromUtf8("actionCreateNewDb"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.actionCreateNewDb)
        self.line_4 = QtGui.QFrame(self.page)
        self.line_4.setGeometry(QtCore.QRect(0, 120, 231, 21))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.page)
        self.line_5.setGeometry(QtCore.QRect(-3, 250, 231, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.page)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(9, 270, 211, 111))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.activeTable = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.activeTable.setEnabled(False)
        self.activeTable.setObjectName(_fromUtf8("activeTable"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.activeTable)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.comboTables = QtGui.QComboBox(self.formLayoutWidget_4)
        self.comboTables.setObjectName(_fromUtf8("comboTables"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboTables)
        self.actionSetActiveTable = QtGui.QPushButton(self.formLayoutWidget_4)
        self.actionSetActiveTable.setObjectName(_fromUtf8("actionSetActiveTable"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.actionSetActiveTable)
        self.actionCreateNewTable = QtGui.QPushButton(self.formLayoutWidget_4)
        self.actionCreateNewTable.setObjectName(_fromUtf8("actionCreateNewTable"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.actionCreateNewTable)
        self.actionDisconnect = QtGui.QPushButton(self.page)
        self.actionDisconnect.setGeometry(QtCore.QRect(10, 480, 211, 51))
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 237, 571))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.groupBox = QtGui.QGroupBox(self.page_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 221, 281))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 211, 251))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.patchSelectionStateBox = QtGui.QComboBox(self.formLayoutWidget_2)
        self.patchSelectionStateBox.setObjectName(_fromUtf8("patchSelectionStateBox"))
        self.patchSelectionStateBox.addItem(_fromUtf8(""))
        self.patchSelectionStateBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.patchSelectionStateBox)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.patchSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.patchSpinBox.setDecimals(0)
        self.patchSpinBox.setMinimum(1.0)
        self.patchSpinBox.setProperty("value", 20.0)
        self.patchSpinBox.setObjectName(_fromUtf8("patchSpinBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.patchSpinBox)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.typeBox = QtGui.QComboBox(self.formLayoutWidget_2)
        self.typeBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.typeBox.setObjectName(_fromUtf8("typeBox"))
        self.typeBox.addItem(_fromUtf8(""))
        self.typeBox.addItem(_fromUtf8(""))
        self.typeBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.typeBox)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.subtypeBox = QtGui.QComboBox(self.formLayoutWidget_2)
        self.subtypeBox.setObjectName(_fromUtf8("subtypeBox"))
        self.subtypeBox.addItem(_fromUtf8(""))
        self.subtypeBox.addItem(_fromUtf8(""))
        self.subtypeBox.addItem(_fromUtf8(""))
        self.subtypeBox.addItem(_fromUtf8(""))
        self.subtypeBox.addItem(_fromUtf8(""))
        self.subtypeBox.addItem(_fromUtf8(""))
        self.subtypeBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.subtypeBox)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.comboAccuracy = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboAccuracy.setObjectName(_fromUtf8("comboAccuracy"))
        self.comboAccuracy.addItem(_fromUtf8(""))
        self.comboAccuracy.addItem(_fromUtf8(""))
        self.comboAccuracy.addItem(_fromUtf8(""))
        self.comboAccuracy.addItem(_fromUtf8(""))
        self.comboAccuracy.addItem(_fromUtf8(""))
        self.comboAccuracy.addItem(_fromUtf8(""))
        self.comboAccuracy.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboAccuracy)
        self.actionCommitGraphics = QtGui.QPushButton(self.formLayoutWidget_2)
        self.actionCommitGraphics.setObjectName(_fromUtf8("actionCommitGraphics"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.actionCommitGraphics)
        self.actionClearGraphics = QtGui.QPushButton(self.formLayoutWidget_2)
        self.actionClearGraphics.setObjectName(_fromUtf8("actionClearGraphics"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.actionClearGraphics)
        self.actionRandomForest = QtGui.QPushButton(self.formLayoutWidget_2)
        self.actionRandomForest.setObjectName(_fromUtf8("actionRandomForest"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.actionRandomForest)
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 221, 241))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.actionClassifyRaster = QtGui.QPushButton(self.groupBox_2)
        self.actionClassifyRaster.setGeometry(QtCore.QRect(20, 30, 91, 23))
        self.actionClassifyRaster.setObjectName(_fromUtf8("actionClassifyRaster"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 237, 571))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.page_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 221, 211))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.tableView = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.tableView.setContentsMargins(-1, -1, 0, -1)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayoutWidget = QtGui.QWidget(self.page_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 230, 221, 251))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.treeView = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.treeView.setContentsMargins(-1, -1, 0, -1)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 237, 571))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.contrastSlider = QtGui.QSlider(self.page_3)
        self.contrastSlider.setGeometry(QtCore.QRect(10, 40, 71, 27))
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.contrastSlider.setTickInterval(5)
        self.contrastSlider.setObjectName(_fromUtf8("contrastSlider"))
        self.actionTest = QtGui.QPushButton(self.page_3)
        self.actionTest.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionLoadBathy = QtGui.QPushButton(self.page_3)
        self.actionLoadBathy.setGeometry(QtCore.QRect(20, 100, 131, 23))
        self.actionLoadBathy.setObjectName(_fromUtf8("actionLoadBathy"))
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 49, 781, 701))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.rasterView = QtGui.QGridLayout(self.gridLayoutWidget)
        self.rasterView.setObjectName(_fromUtf8("rasterView"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 470, 231, 201))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.previewView = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.previewView.setObjectName(_fromUtf8("previewView"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(250, 490, 511, 181))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.cmdView = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.cmdView.setObjectName(_fromUtf8("cmdView"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(580, 470, 171, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.xLabel = QtGui.QLabel(self.tab)
        self.xLabel.setGeometry(QtCore.QRect(590, 470, 81, 16))
        self.xLabel.setObjectName(_fromUtf8("xLabel"))
        self.yLabel = QtGui.QLabel(self.tab)
        self.yLabel.setGeometry(QtCore.QRect(690, 470, 61, 16))
        self.yLabel.setObjectName(_fromUtf8("yLabel"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(9, 9, 761, 661))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.databaseView = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.databaseView.setObjectName(_fromUtf8("databaseView"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.toolImport = QtGui.QToolButton(self.centralwidget)
        self.toolImport.setGeometry(QtCore.QRect(10, 10, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/import_backscatter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolImport.setIcon(icon1)
        self.toolImport.setIconSize(QtCore.QSize(32, 32))
        self.toolImport.setObjectName(_fromUtf8("toolImport"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(-13, 39, 1071, 21))
        self.line_6.setAutoFillBackground(True)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.toolExport = QtGui.QToolButton(self.centralwidget)
        self.toolExport.setGeometry(QtCore.QRect(120, 10, 31, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolExport.setIcon(icon2)
        self.toolExport.setIconSize(QtCore.QSize(32, 32))
        self.toolExport.setObjectName(_fromUtf8("toolExport"))
        self.dbStatus = QtGui.QLineEdit(self.centralwidget)
        self.dbStatus.setGeometry(QtCore.QRect(910, 10, 121, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.dbStatus.setPalette(palette)
        self.dbStatus.setAutoFillBackground(True)
        self.dbStatus.setObjectName(_fromUtf8("dbStatus"))
        self.toolImportBathy = QtGui.QToolButton(self.centralwidget)
        self.toolImportBathy.setGeometry(QtCore.QRect(40, 10, 31, 31))
        self.toolImportBathy.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/import_bathy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolImportBathy.setIcon(icon3)
        self.toolImportBathy.setIconSize(QtCore.QSize(32, 32))
        self.toolImportBathy.setObjectName(_fromUtf8("toolImportBathy"))
        self.toolDeleteRaster = QtGui.QToolButton(self.centralwidget)
        self.toolDeleteRaster.setGeometry(QtCore.QRect(150, 10, 31, 31))
        self.toolDeleteRaster.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/delete_rasters.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolDeleteRaster.setIcon(icon4)
        self.toolDeleteRaster.setIconSize(QtCore.QSize(32, 32))
        self.toolDeleteRaster.setObjectName(_fromUtf8("toolDeleteRaster"))
        self.toolImportCurrents = QtGui.QToolButton(self.centralwidget)
        self.toolImportCurrents.setGeometry(QtCore.QRect(70, 10, 31, 31))
        self.toolImportCurrents.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/import_current.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolImportCurrents.setIcon(icon5)
        self.toolImportCurrents.setIconSize(QtCore.QSize(32, 32))
        self.toolImportCurrents.setObjectName(_fromUtf8("toolImportCurrents"))
        self.line_6.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.tabWidget.raise_()
        self.toolImport.raise_()
        self.toolExport.raise_()
        self.dbStatus.raise_()
        self.toolImportBathy.raise_()
        self.toolDeleteRaster.raise_()
        self.toolImportCurrents.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRasters = QtGui.QMenu(self.menubar)
        self.menuRasters.setObjectName(_fromUtf8("menuRasters"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionDeleteSelected = QtGui.QAction(MainWindow)
        self.actionDeleteSelected.setObjectName(_fromUtf8("actionDeleteSelected"))
        self.actionNew_Table = QtGui.QAction(MainWindow)
        self.actionNew_Table.setWhatsThis(_fromUtf8(""))
        self.actionNew_Table.setObjectName(_fromUtf8("actionNew_Table"))
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuRasters.addAction(self.actionDeleteSelected)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRasters.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.patchSelectionStateBox.setCurrentIndex(1)
        self.subtypeBox.setCurrentIndex(1)
        self.comboAccuracy.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.dbHostEdit, self.dbUserEdit)
        MainWindow.setTabOrder(self.dbUserEdit, self.dbPasswdEdit)
        MainWindow.setTabOrder(self.dbPasswdEdit, self.patchSpinBox)
        MainWindow.setTabOrder(self.patchSpinBox, self.actionCommitGraphics)
        MainWindow.setTabOrder(self.actionCommitGraphics, self.patchSelectionStateBox)
        MainWindow.setTabOrder(self.patchSelectionStateBox, self.typeBox)
        MainWindow.setTabOrder(self.typeBox, self.contrastSlider)
        MainWindow.setTabOrder(self.contrastSlider, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ClassiPy 2.0.0", None))
        self.label_2.setText(_translate("MainWindow", "Host:", None))
        self.dbHostEdit.setToolTip(_translate("MainWindow", "\'localhost\' or IP of SQL Server.", None))
        self.dbHostEdit.setStatusTip(_translate("MainWindow", "This value will be either \'localhost\' or the IP address of the SQL server.", None))
        self.dbHostEdit.setText(_translate("MainWindow", "localhost", None))
        self.label_3.setText(_translate("MainWindow", "Username:", None))
        self.dbUserEdit.setText(_translate("MainWindow", "hakaimarine", None))
        self.label_4.setText(_translate("MainWindow", "Password:", None))
        self.dbPasswdEdit.setText(_translate("MainWindow", "hakaiblue", None))
        self.actionConnectDb.setToolTip(_translate("MainWindow", "Connect to SQL Server", None))
        self.actionConnectDb.setStatusTip(_translate("MainWindow", "Connect to SQL Server", None))
        self.actionConnectDb.setText(_translate("MainWindow", "Connect", None))
        self.label_10.setText(_translate("MainWindow", "Databases:", None))
        self.actionSetActiveDb.setText(_translate("MainWindow", "Set as Active DB", None))
        self.label_11.setText(_translate("MainWindow", "Active DB:", None))
        self.actionCreateNewDb.setText(_translate("MainWindow", "Create New DB", None))
        self.label_9.setText(_translate("MainWindow", "Active Table:", None))
        self.label_12.setText(_translate("MainWindow", "Tables:", None))
        self.actionSetActiveTable.setText(_translate("MainWindow", "Set as Active Table", None))
        self.actionCreateNewTable.setText(_translate("MainWindow", "Create New Table", None))
        self.actionDisconnect.setText(_translate("MainWindow", "DISCONNECT", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Database Tools", None))
        self.groupBox.setTitle(_translate("MainWindow", "Add Known Types (Training)", None))
        self.label_7.setText(_translate("MainWindow", "Selection Mode", None))
        self.patchSelectionStateBox.setItemText(0, _translate("MainWindow", "Enabled", None))
        self.patchSelectionStateBox.setItemText(1, _translate("MainWindow", "Disabled", None))
        self.label_6.setText(_translate("MainWindow", "Patch Size:", None))
        self.patchSpinBox.setSuffix(_translate("MainWindow", " Pixels", None))
        self.label_5.setText(_translate("MainWindow", "Type:", None))
        self.typeBox.setItemText(0, _translate("MainWindow", "Vegetation", None))
        self.typeBox.setItemText(1, _translate("MainWindow", "Sediment", None))
        self.typeBox.setItemText(2, _translate("MainWindow", "Rocks", None))
        self.label_13.setText(_translate("MainWindow", "Subtype:", None))
        self.subtypeBox.setItemText(0, _translate("MainWindow", "Kelp", None))
        self.subtypeBox.setItemText(1, _translate("MainWindow", "Seagrass", None))
        self.subtypeBox.setItemText(2, _translate("MainWindow", "Sand", None))
        self.subtypeBox.setItemText(3, _translate("MainWindow", "Mud", None))
        self.subtypeBox.setItemText(4, _translate("MainWindow", "Gravel", None))
        self.subtypeBox.setItemText(5, _translate("MainWindow", "Boulder", None))
        self.subtypeBox.setItemText(6, _translate("MainWindow", "Bedrock", None))
        self.label_8.setText(_translate("MainWindow", "Accuracy Threshold", None))
        self.comboAccuracy.setToolTip(_translate("MainWindow", "Minimum classification accuracy required for database to accept selections.", None))
        self.comboAccuracy.setItemText(0, _translate("MainWindow", "70", None))
        self.comboAccuracy.setItemText(1, _translate("MainWindow", "75", None))
        self.comboAccuracy.setItemText(2, _translate("MainWindow", "80", None))
        self.comboAccuracy.setItemText(3, _translate("MainWindow", "85", None))
        self.comboAccuracy.setItemText(4, _translate("MainWindow", "90", None))
        self.comboAccuracy.setItemText(5, _translate("MainWindow", "95", None))
        self.comboAccuracy.setItemText(6, _translate("MainWindow", "100", None))
        self.actionCommitGraphics.setStatusTip(_translate("MainWindow", "Commit selection of known bottom types to the project database.", None))
        self.actionCommitGraphics.setText(_translate("MainWindow", "Commit", None))
        self.actionClearGraphics.setStatusTip(_translate("MainWindow", "Clear selected patches.", None))
        self.actionClearGraphics.setText(_translate("MainWindow", "Clear", None))
        self.actionRandomForest.setToolTip(_translate("MainWindow", "Perform a test classification on the selected areas.", None))
        self.actionRandomForest.setText(_translate("MainWindow", "R.F. Metrics", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Classify Raster", None))
        self.actionClassifyRaster.setText(_translate("MainWindow", "Classify Raster", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Classification Tools", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Properties", None))
        self.actionTest.setText(_translate("MainWindow", "test", None))
        self.actionLoadBathy.setText(_translate("MainWindow", "Test Load Bathy", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Arc Tools", None))
        self.label.setText(_translate("MainWindow", "X:                              Y:", None))
        self.xLabel.setText(_translate("MainWindow", "0", None))
        self.yLabel.setText(_translate("MainWindow", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "View", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Database", None))
        self.toolImport.setToolTip(_translate("MainWindow", "Import Raster", None))
        self.toolImport.setStatusTip(_translate("MainWindow", "Import Raster", None))
        self.toolImport.setText(_translate("MainWindow", "...", None))
        self.toolExport.setToolTip(_translate("MainWindow", "Export Raster", None))
        self.toolExport.setStatusTip(_translate("MainWindow", "Export Raster", None))
        self.toolExport.setText(_translate("MainWindow", "...", None))
        self.dbStatus.setStatusTip(_translate("MainWindow", "Database Server Status", None))
        self.dbStatus.setText(_translate("MainWindow", "Database Disconnected", None))
        self.toolImportBathy.setStatusTip(_translate("MainWindow", "Import Bathymetry", None))
        self.toolDeleteRaster.setStatusTip(_translate("MainWindow", "Delete Selected Raster", None))
        self.toolImportCurrents.setStatusTip(_translate("MainWindow", "Import Ocean Currents Model", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRasters.setTitle(_translate("MainWindow", "Rasters", None))
        self.actionImport.setText(_translate("MainWindow", "Import...", None))
        self.actionImport.setStatusTip(_translate("MainWindow", "Import a raster (.TIF) file.", None))
        self.actionExport.setText(_translate("MainWindow", "Export...", None))
        self.actionExport.setStatusTip(_translate("MainWindow", "Export current classification.", None))
        self.actionDeleteSelected.setText(_translate("MainWindow", "Delete Selected", None))
        self.actionDeleteSelected.setStatusTip(_translate("MainWindow", "Delete all selected Rasters in the tree view.", None))
        self.actionNew_Table.setText(_translate("MainWindow", "New Table...", None))
        self.actionNew_Table.setToolTip(_translate("MainWindow", "New Table", None))
        self.actionNew_Table.setStatusTip(_translate("MainWindow", "Create a new classification table within open database. Database connection required.", None))

